level3/translator-app/config/routes.rb
Rails.application.routes.draw do
  scope module: :public do
    root 'pages#main'
  end

  devise_for :users, controllers: {
    sessions: 'user_account/authentification/sessions',
    registrations: 'user_account/authentification/registrations',
    passwords: 'user_account/authentification/passwords',
  }

  namespace :user_account do
    resources :dashboards, only: :index
    resources :messages, only: %i(index show create)

    resources :tags, param: :name, only: %i() do
      scope module: :tags do
        resources :messages, only: :index
      end
    end
  end

  namespace :api, defaults: { format: :json } do
    scope module: :authentification do
      resources :sessions, only: :create
    end

    resources :messages, only: %i(index show)

    resources :tags, param: :name, only: %i() do
      scope module: :tags do
        resources :messages, only: :index
      end
    end
  end
end

level3/translator-app/app/controllers/user_account/application_controller.rb
# frozen_string_literal: true

module UserAccount
  class ApplicationController < ActionController::Base
    include Pagy::Backend

    layout 'user_account/layouts/application'

    before_action :authenticate_user!
  end
end

level3/translator-app/app/controllers/user_account/authentification/passwords_controller.rb
# frozen_string_literal: true

module UserAccount
  module Authentification
    class PasswordsController < Devise::PasswordsController
      def new # rubocop:disable Lint/UselessMethodDefinition
        super
      end

      def create # rubocop:disable Lint/UselessMethodDefinition
        super
      end

      def edit # rubocop:disable Lint/UselessMethodDefinition
        super
      end

      def update # rubocop:disable Lint/UselessMethodDefinition
        super
      end

      protected

      def after_resetting_password_path_for(resource) # rubocop:disable Lint/UselessMethodDefinition
        super(resource)
      end

      # The path used after sending reset password instructions
      def after_sending_reset_password_instructions_path_for(resource_name) # rubocop:disable Lint/UselessMethodDefinition
        super(resource_name)
      end
    end
  end
end

level3/translator-app/app/controllers/user_account/authentification/registrations_controller.rb
# frozen_string_literal: true

module UserAccount
  module Authentification
    class RegistrationsController < Devise::RegistrationsController
      include SkipBullet

      before_action :configure_sign_up_params, only: :create
      before_action :configure_account_update_params, only: :update
      around_action :skip_bullet, only: :destroy

      def new # rubocop:disable Lint/UselessMethodDefinition
        super
      end

      def create # rubocop:disable Lint/UselessMethodDefinition
        super
      end

      def edit # rubocop:disable Lint/UselessMethodDefinition
        super
      end

      def update
        # if update_resource(current_user, account_update_params)
        if resource.update_without_password(account_update_params)
          # set_flash_message_for_update(resource, current_user.unconfirmed_email)
          bypass_sign_in(current_user, scope: :user) if sign_in_after_change_password?
        else
          flash[:error] = resource.errors.full_messages.first
          clean_up_passwords(current_user)
        end

        pp resource.errors

        redirect_to user_account_messages_path
      end

      def destroy # rubocop:disable Lint/UselessMethodDefinition
        super
      end

      protected

      def configure_sign_up_params
        devise_parameter_sanitizer.permit(
          :sign_up,
          keys: %i(first_name last_name language)
        )
      end

      def configure_account_update_params
        devise_parameter_sanitizer.permit(
          :account_update,
          keys: %i(first_name last_name language)
        )
      end

      def after_sign_up_path_for(_resource)
        user_account_dashboards_path
      end

      def after_inactive_sign_up_path_for(_resource)
        user_account_dashboards_path
      end
    end
  end
end

level3/translator-app/app/controllers/user_account/authentification/sessions_controller.rb
# frozen_string_literal: true

module UserAccount
  module Authentification
    class SessionsController < Devise::SessionsController
      respond_to :html

      def new # rubocop:disable Lint/UselessMethodDefinition
        super
      end

      def create # rubocop:disable Lint/UselessMethodDefinition
        super
      end

      def destroy # rubocop:disable Lint/UselessMethodDefinition
        super
      end

      protected

      def after_sign_in_path_for(_resource)
        session[:previous_url] || user_account_dashboards_path
      end
    end
  end
end

level3/translator-app/app/controllers/user_account/dashboards_controller.rb
# frozen_string_literal: true

module UserAccount
  class DashboardsController < UserAccount::ApplicationController
    def index
      @users_count = User.count
      @messages_count = Message.count
      @tags_count = Tag.count
    end
  end
end

level3/translator-app/app/controllers/user_account/messages_controller.rb
# frozen_string_literal: true

module UserAccount
  class MessagesController < UserAccount::ApplicationController
    def index
      @pagy, @messages = pagy(Message.includes(:user, :tag).order(created_at: :desc).all)
      @tags = Tag.all
    end

    def show
      @message = Message.includes(:user, :tag).find(params[:id])
    end

    def create
      @message = Message.new(messages_params.merge(user_id: current_user.id))

      if @message.save
        flash[:success] = 'Message created'
      else
        flash[:error] = 'Error on message'
      end

      pp @message.errors

      redirect_to user_account_messages_path
    end

    private

    def messages_params
      params.require(:message).permit(:french_content, :piou_content, :tag_id)
    end
  end
end

level3/translator-app/app/controllers/user_account/tags/messages_controller.rb
# frozen_string_literal: true

module UserAccount
  module Tags
    class MessagesController < UserAccount::ApplicationController
      def index
        @pagy, @messages = pagy(Message.includes(:user, :tag).where(tags: { name: params[:tag_name] }))
        @tags = Tag.all
      end
    end
  end
end

level3/translator-app/app/views/user_account/shared/_messages.html.slim
div
  .hidden.sm:block.mb-2
    .border-b.border-gray-200
      nav.-mb-px.flex[aria-label="Tabs"]
        - @tags.each do |tag|
          = link_to tag.name, user_account_tag_messages_path(tag.name), class: "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300 w-1/4 py-4 px-1 text-center border-b-2 font-medium text-sm"

.overflow-hidden.bg-white.shadow.sm:rounded-md
  ul.divide-y.divide-gray-200[role="list"]
    - @messages.each do |message|
      li
        = link_to user_account_message_path(message), class: 'lock hover:bg-gray-50' do
          .flex.items-center.px-4.py-4.sm:px-6
            .min-w-0.flex-1.sm:flex.sm:items-center.sm:justify-between
              .truncate
                .flex.text-sm
                  p.truncate.font-medium.text-indigo-600
                    = "#{message.user.first_name} #{message.user.last_name}"
                  p.ml-3.flex-shrink-0.font-normal.text-gray-500
                    = message.created_at.strftime('%d/%m/%Y')
                  p.ml-3.flex-shrink-0.font-normal.text-gray-500
                    - if message.tag.present?
                      span.inline-flex.items-center.rounded-full.bg-red-100.px-3.py-0.5.text-sm.font-medium.text-red-800
                        = message.tag.name
                .mt-2.flex
                  .flex.items-center.text-sm.text-gray-500
                    span Fr |
                    p.ml-3 = message.french_content
                .mt-2.flex
                  .flex.items-center.text-sm.text-gray-500
                    span Piou |
                    p.ml-3 = message.piou_content
            .ml-5.flex-shrink-0
              svg.h-5.w-5.text-gray-400[xmlns="http://www.w3.org/2000/svg" viewbox="0 0 20 20" fill="currentColor" aria-hidden="true"]
                path[fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd"]

- if @pagy.pages > 1
  == pagy_nav(@pagy)