level3/translator-app/config/routes.rb
Rails.application.routes.draw do
  scope module: :public do
    root 'pages#main'
  end

  devise_for :users, controllers: {
    sessions: 'user_account/authentification/sessions',
    registrations: 'user_account/authentification/registrations',
    passwords: 'user_account/authentification/passwords',
  }

  namespace :user_account do
    resources :dashboards, only: :index
    resources :messages, only: %i(index show create)

    resources :tags, param: :name, only: %i() do
      scope module: :tags do
        resources :messages, only: :index
      end
    end
  end

  namespace :api, defaults: { format: :json } do
    scope module: :authentification do
      resources :sessions, only: :create
    end

    resources :messages, only: %i(index show)

    resources :tags, param: :name, only: %i() do
      scope module: :tags do
        resources :messages, only: :index
      end
    end
  end
end

level3/translator-app/app/controllers/api/authentification/sessions_controller.rb
# frozen_string_literal: true

module Api
  module Authentification
    class SessionsController < Api::ApplicationController
      skip_before_action :process_token, :authenticate_user!

      def create
        @user = User.find_by(email: user_params[:email])

        if @user&.valid_password?(user_params[:password])
          @jwt_token = @user.generate_jwt
        else
          head :unauthorized
        end
      end

      private

      def user_params
        params.require(:user).permit(:email, :password)
      end
    end
  end
end

level3/translator-app/app/controllers/user_account/authentification/passwords_controller.rb
# frozen_string_literal: true

module UserAccount
  module Authentification
    class PasswordsController < Devise::PasswordsController
      def new # rubocop:disable Lint/UselessMethodDefinition
        super
      end

      def create # rubocop:disable Lint/UselessMethodDefinition
        super
      end

      def edit # rubocop:disable Lint/UselessMethodDefinition
        super
      end

      def update # rubocop:disable Lint/UselessMethodDefinition
        super
      end

      protected

      def after_resetting_password_path_for(resource) # rubocop:disable Lint/UselessMethodDefinition
        super(resource)
      end

      # The path used after sending reset password instructions
      def after_sending_reset_password_instructions_path_for(resource_name) # rubocop:disable Lint/UselessMethodDefinition
        super(resource_name)
      end
    end
  end
end

level3/translator-app/app/controllers/user_account/authentification/registrations_controller.rb
# frozen_string_literal: true

module UserAccount
  module Authentification
    class RegistrationsController < Devise::RegistrationsController
      include SkipBullet

      before_action :configure_sign_up_params, only: :create
      before_action :configure_account_update_params, only: :update
      around_action :skip_bullet, only: :destroy

      def new # rubocop:disable Lint/UselessMethodDefinition
        super
      end

      def create # rubocop:disable Lint/UselessMethodDefinition
        super
      end

      def edit # rubocop:disable Lint/UselessMethodDefinition
        super
      end

      def update
        # if update_resource(current_user, account_update_params)
        if resource.update_without_password(account_update_params)
          # set_flash_message_for_update(resource, current_user.unconfirmed_email)
          bypass_sign_in(current_user, scope: :user) if sign_in_after_change_password?
        else
          flash[:error] = resource.errors.full_messages.first
          clean_up_passwords(current_user)
        end

        pp resource.errors

        redirect_to user_account_messages_path
      end

      def destroy # rubocop:disable Lint/UselessMethodDefinition
        super
      end

      protected

      def configure_sign_up_params
        devise_parameter_sanitizer.permit(
          :sign_up,
          keys: %i(first_name last_name language)
        )
      end

      def configure_account_update_params
        devise_parameter_sanitizer.permit(
          :account_update,
          keys: %i(first_name last_name language)
        )
      end

      def after_sign_up_path_for(_resource)
        user_account_dashboards_path
      end

      def after_inactive_sign_up_path_for(_resource)
        user_account_dashboards_path
      end
    end
  end
end

level3/translator-app/app/controllers/user_account/authentification/sessions_controller.rb
# frozen_string_literal: true

module UserAccount
  module Authentification
    class SessionsController < Devise::SessionsController
      respond_to :html

      def new # rubocop:disable Lint/UselessMethodDefinition
        super
      end

      def create # rubocop:disable Lint/UselessMethodDefinition
        super
      end

      def destroy # rubocop:disable Lint/UselessMethodDefinition
        super
      end

      protected

      def after_sign_in_path_for(_resource)
        session[:previous_url] || user_account_dashboards_path
      end
    end
  end
end

level3/translator-app/app/views/user_account/authentification/shared/_error_messages.html.slim
- if resource.errors.any?
  .rounded-md.bg-red-50.p-4
    .flex
      .flex-shrink-0
        svg.h-5.w-5.text-red-400[xmlns="http://www.w3.org/2000/svg" viewbox="0 0 20 20" fill="currentColor" aria-hidden="true"]
          path[fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z" clip-rule="evenodd"]
      .ml-3
        h3.text-sm.font-medium.text-red-800
          | There were 2 errors with your submission
        .mt-2.text-sm.text-red-700
          ul.list-disc.space-y-1.pl-5[role="list"]
            li
              = t("errors.messages.not_saved", count: resource.errors.count, resource: resource.class.model_name.human.downcase)
            - resource.errors.full_messages.each do |message|
              li
                = message

level3/translator-app/app/views/user_account/authentification/shared/_links.html.slim
- if controller_name != 'sessions'
  .flex.items-center.justify-between
    .flex.items-center
      | I already have an account.

    .text-sm
      = link_to "Sign in", new_session_path(resource_name), class: 'font-medium text-indigo-600 hover:text-indigo-500'
  br

- if devise_mapping.registerable? && controller_name != 'registrations'
  .flex.items-center.justify-between
    .flex.items-center
      | Not registered ?

    .text-sm
      = link_to "Sign up", new_registration_path(resource_name), class: 'font-medium text-indigo-600 hover:text-indigo-500'